#!/bin/sh -
# SPDX-License-Identifier: 0BSD
# Copyright 2016-12-06 Alexander Kozhevnikov <mentalisttraceur@gmail.com>

diff -U0 "$@" \
| sed '1,2 d; s/^-/< /; s/^+/> /; /^[^@]/ { s/%/%1/g; s/@/%2/g; }' \
| tr '\0' @ \
| awk '
   /^>/ {
    if(op ~ "^c$")
    {
     print "---"
    }
    op = ""
   }
   /^@/ {
    op = ""
    split(substr($2, 2), old, ",")
    split(substr($3, 2), new, ",")
    old[3] = old[1] + old[2] - 1
    if(old[3] > old[1])
    {
     old[3] = old[1] "," old[3]
    }
    else
    {
     if(old[2] ~ "^0$")
     {
      op = "a"
     }
     old[3] = old[1]
    }
    new[3] = new[1] + new[2] - 1
    if(new[3] > new[1])
    {
     new[3] = new[1] "," new[3]
    }
    else
    {
     if(new[2] ~ "^0$")
     {
      op = "d"
     }
     new[3] = new[1]
    }
    if(op ~ "^$")
    {
     op = "c"
    }
    $0 = old[3] op new[3]
   }
   { print }
  ' \
| tr @ '\0' \
| sed 's/%2/@/g; s/%1/%/g'
